### ISSUE TITLE
`normCounts<-` method stores normalized counts in `normCounts` instead of `normalizedCounts`

### ISSUE THREAD

**Issue by drisso** [drisso/EDASeq#1]

**Comment by DarioS** [comment]
Could this update also fix between-lane normalised data visualisation?

```r
> all(is.finite(readCounts))
[1] TRUE
> any(is.na(readCounts))
[1] FALSE
> AMLExpressionSet <- newSeqExpressionSet(readCounts)
> AMLExpressionSet <- betweenLaneNormalization(AMLExpressionSet)
> meanVarPlot(AMLExpressionSet)
Error in quantile.default(m, probs = 0.9) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
```

Also, I'm going to present a workshop on Friday next week. Do you anticipate these updates will be availalble from Bioconductor before then for attendees to install easily?

**Comment by drisso** [comment]
Hi Dario,

the bug fix is implemented in the develop branch here on GitHub. If you can try it out, it would be good to see if it solves all your problems. I plan to merge it to master and to Bioconductor later today after some tests.

I'm not able to reproduce the error that you just posted, do you have a reproducible example that I can use to track it down?

**Comment by DarioS** [comment]
I installed using `devtools::install_github("drisso/EDASeq")` and it still doesn't use the normalised counts if they're added after the SeqExpressionSet is first constructed. The addition method continues to add something called `normCounts`.

Here's the code again

```r
counts <- matrix(c(seq(100, 1000, 100),
                   seq(100, 1000, 100) * 2,
                   seq(100, 1000, 100) * 3), ncol = 3)
sizedCounts <- matrix(rep(seq(100, 1000, 100) * 3, 3), ncol = 3)
SES <- newSeqExpressionSet(counts)
meanVarPlot(SES) # As expected with raw counts.
normCounts(SES) <- sizedCounts
meanVarPlot(SES) # Variance should be 0 if sizedCounts was utilised but looks same as previous plot.
names(assayData(SES)) # Duplicated entries for normalised counts remain.
```

For the `betweenLaneNormalization` issue, firstly download [counts.txt](https://github.com/SydneyBioX/localWorkshop/raw/master/data/counts.txt) (16 MB). Then,

```r
AMLcounts <- as.matrix(read.delim("counts.txt")) # GEO GSE106291
SEScancer <- newSeqExpressionSet(AMLcounts)
SEScancer <- betweenLaneNormalization(SEScancer)
meanVarPlot(SEScancer)

Error in quantile.default(m, probs = 0.9) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
```

But 

```r
> any(is.na(AMLcounts) | is.nan(AMLcounts))
[1] FALSE
```

**Comment by drisso** [comment]
The new code is in the develop branch, you can download that version using

```{r}
devtools::install_github("drisso/EDASeq@develop")
```

I will look into the second issue.

**Comment by drisso** [comment]
Hi @DarioS 

about your second issue, this is not a bug in `EDASeq`, but it is due to the default normalization in `betweenLaneNormalization`. By default, it scales the counts by the median, and when the median is 0 it returns Inf or NA. Filtering the non-expressed genes and/or using the upper quartile (`method="upper"`) would solve the issue.

The fact that the counts are not NA is irrelevant, since `meanVarPlot` plots the normalized counts:

```{r}
> any(is.na(normCounts(SEScancer)))
[1] TRUE
```

**Comment by drisso** [comment]
I've merged the change to master and to Bioc devel. Keep in mind that it will take 1-2 days to build on Bioconductor, but after that you should be able to get this version when using the devel version of Bioconductor.

**Comment by DarioS** [comment]
Since it's a bug rather than a new feature or API change, could you also port the changes back to the release branch of Bioconductor? It would make installation of the package for workshop attendees easier if they didn't have to learn about `useDevel()`.

**Comment by drisso** [comment]
It makes sense. I will fix the bug in release as well. It should be up in 1-2 days, because of the Bioc build system.
