### ISSUE TITLE
error in generating biasPlot after withinLaneNormalization

### ISSUE THREAD

**Issue by nfancy** [drisso/EDASeq#5]
Hi 

Thank you for this excellent package to dig out more about biases in our data. I have recently used your package and found 2 of my 20 samples have high GC bias. So, I decided to normalise for that, first I used upper normalisation and checked the biasPlot again and it worked. However, after using median normalisation I can't generate the biasPlot. I am having the following error.

> biasPlot(dataWithin, "GC", log=TRUE, xlim = c(0,100), ylim=c(0,2), legend = FALSE, col = icolor, lwd = 4)
Error in lowess(y[x[, i] <= cutoff], x[x[, i] <= cutoff, i]) : 
  'delta' must be finite and > 0

Any suggestion how to solve this issue?

Best wishes
Nurun

**Comment by drisso** [comment]
Hi @nfancy 

Unfortunately, I cannot help much without a minimal working example. Can you provide one? Perhaps you can provide a subset of your data without gene / sample IDs that would cause the same error?

My wild guess just by googling the error is that you have NA's or Inf values in your normalized data. This might happen e.g. if one of your samples has a median of 0 (i.e., more than half of the genes have 0 reads). If that's the case either filtering lowly expressed genes, or using another within-lane normalization might work.
