### ISSUE TITLE
Adding title to plots

### ISSUE THREAD

**Issue by GrantHov** [drisso/EDASeq#7]
Hello,

How is it possible to add title for plotPCA or plotRLE plots?

Thanks,

**Comment by drisso** [comment]
Hi @GrantHov 

the "main" argument can be used to add plot titles as it is passed to the base `plot()` function.

For instance, modifying the example in the plotRLE man page, you can do:

```{r}
library(yeastRNASeq)
data(geneLevelData)
     
mat <- as.matrix(geneLevelData)
     
data <- newSeqExpressionSet(mat,
                            phenoData=AnnotatedDataFrame(
                                      data.frame(conditions=factor(c("mut", "mut", "wt", "wt")),
                                                 row.names=colnames(geneLevelData))))
plotRLE(data, col=rep(2:3, each=2), main="RLE plot")
```

Please, use the official Bioconductor support site (http://support.bioconductor.org) for this type of questions (e.g., usage questions of the main functions of the package). That is the preferred way of communication for getting help for this package, which means that you will generally get a response faster.

**Comment by GrantHov** [comment]
Thanks a lot, I'll take into account your suggestion regarding further postings.
