### ISSUE TITLE
EDASeq cannot be installed for BioC 3.12

### ISSUE THREAD

**Issue by mbstadler** [drisso/EDASeq#8]
`EDASeq` imports `DESeq`, which is depreciated and not available for BioC 3.12.

Interestingly, the BioC builders currently show `EDASeq` as building ok (maybe it was built when `DESeq` was still available?).

Steps to reproduce:
```
> BiocManager::install("EDASeq")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.0 (2020-04-24)
Installing package(s) 'EDASeq'
Warning: dependency 'DESeq' is not available
trying URL 'https://ftp.gwdg.de/pub/misc/bioconductor//packages/3.12/bioc/src/contrib/EDASeq_2.23.0.tar.gz'
Content type 'application/octet-stream' length 1033478 bytes (1009 KB)
==================================================
downloaded 1009 KB

ERROR: dependency 'DESeq' is not available for package 'EDASeq'
* removing '/tungstenfs/groups/gbioinfo/Appz/R/BioC/R-4.0-release-foss-2019b_BioC-3.12-devel-foss-2019b/EDASeq'

The downloaded source packages are in
        '/tungstenfs/scratch/gbioinfo/scratch_xenon6/stadler/RtmpYPfp5z/downloaded_packages'
Warning message:
In install.packages(...) :
  installation of package 'EDASeq' had non-zero exit status

> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /tungstenfs/groups/gbioinfo/Appz/easybuild/software/OpenBLAS/0.3.7-GCC-8.3.0/lib/libopenblas_skylakex-r0.3.7.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RColorBrewer_1.1-2

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.0      tools_4.0.0         fortunes_1.5-4
>
```

**Comment by drisso** [comment]
Thanks @mbstadler!

I didn't realize that DESeq is deprecated! I should be able to switch to DESeq2 (or avoid the dependency altogether). I will try to fix this ASAP!

**Comment by drisso** [comment]
I've just pushed a commit that removes the dependency on DESeq and updates the vignette to show how to use EDASeq with DESeq2.

@mikelove would you mind having a quick look here:
https://github.com/drisso/EDASeq/blob/master/vignettes/EDASeq.Rmd#L442
to confirm that I understood correctly how to pass the offsets to DESeq2?

**Comment by drisso** [comment]
This change should be propagated to Bioc 3.12 in a couple of days..

**Comment by mikelove** [comment]
That looks correct. We recommend one more step before assignment:

```
normFactors <- normFactors / exp(rowMeans(log(normFactors)))
normalizationFactors(dds) <- normFactors
```

these lines ensure that the geometric mean across sample is 1, so that scaled counts `counts(dds, normalized=TRUE)` are not too far off from original counts.

**Comment by drisso** [comment]
Great! I will add this!

**Comment by mbstadler** [comment]
Thanks a lot for the quick fix!
